Flux et article
gtaigniere/flux-rss pull request #4
Opened 2020-12-03 21:22 UTC by gillout

2020-12-04 00:38 UTC, matthieuaudemard commented on .gitignore
> +/config/config.php
je te recommande d'utiliser le site [gitignore.io](https://www.toptal.com/developers/gitignore) pour la création de fichier gitignore. Tu rentres dans le formulaire les outils que tu utilies (par ex sur ce projet : phpstorm composer) et il te génère un gitignore que tu n'as plus qu'à copier coller dans ton fichier et à personnaliser avec tes préférences

2020-12-04 02:07 UTC, matthieuaudemard requested changes
Globalement tu en fais trop. Il y a bcp de chose que tu as implémenté qui pour l'instant ne te servent pas. C'est le même principe que de mettre le ';' avant d'avoir entré les paramètres de ta fonction.

Je t'ai créé des issues pour te donner un point de départ. Après avoir corrigé ta PR tu feras directement #7  en mettant en place la structure minimal de ton architecture (controleur etc etc) pour l'affichage de la maquette que je t'ai fournie. Essaye d'utiliser bootstrap, c'est énormément utilisé en entreprise. Si tu t'y entraines bien ça te permet de rajouter une ligne dans ton CV. A l'heure actuellement c'est vraiment un plus dans un entretien et un gain de temps sur un projet.

2020-12-04 02:07 UTC, matthieuaudemard commented on Controller/ArticleController.php
> +    private $db;
tu as déjà un champ $db dans ta classe mère. Si tu le met en protected tu n'as pas besoin de le mettre dans tes classes filles.

2020-12-04 02:07 UTC, matthieuaudemard commented on Controller/ArticleController.php
> +    public function __construct(PDO $db)
J'avais créé la classe [App du projet book](https://github.com/gillout/book-store/blob/develop/src/app/App.php) afin d'éviter de passer un PDO en paramètre du constructeur de mes Controllers. ce qui te permet d'injecter ta bd dans le constructeur du manager à l'aide de fonctions statiques (cf : [BookController](https://github.com/gillout/book-store/blob/8e1b2a4f66dd38f7f20bcb688ef3dbeaf1160a97/src/app/back/controller/BookController.php#L25))

2020-12-04 02:07 UTC, matthieuaudemard commented on Controller/ArticleController.php
> +            $article->setReleaseDate($article->getReleaseDate());
- là je comprend pas trop ce que tu cherches à faire ? en gros `$var = $var` ?
- tu peux aussi potentiellement vérifier que tous tes flux sont à jour. si l'idée te plait et pour te retrouver plus facilement quand tu souhaiteras implémenté cette fonctionnalité, tu peux laisser un commentaire de ce type : 
```php
// TODO: actualiser les différents flux
```

2020-12-04 02:07 UTC, matthieuaudemard commented on Controller/ArticleController.php
> +            $article->setReleaseDate($article->getReleaseDate());
ici non plus je comprend pas l'utilité de cette ligne

2020-12-04 02:07 UTC, matthieuaudemard commented on Controller/ArticleController.php
> +        } else {
t'es pas obligé de faire un `if ... else`. tu peux imaginer par exemple une condition dans ton template : 
```php
<?php if ($article === null) : echo '<p>aucun article correspondant</p>'; ?>
```

2020-12-04 02:07 UTC, matthieuaudemard commented on Controller/FluxController.php
> +    private $db;
même remarque, tu as un `$db`dans ta classe mère.

2020-12-04 02:07 UTC, matthieuaudemard commented on Controller/FluxController.php
> +    public function __construct(PDO $db)
même remarque que dans ton ArticleController : regarde comment j'avais fait avec la classe App

2020-12-04 02:07 UTC, matthieuaudemard commented on Controller/FluxController.php
> +            $flux->setLastBuildDate($flux->getLastBuildDate());
je comprend toujours pas 😉

2020-12-04 02:07 UTC, matthieuaudemard commented on Controller/FluxController.php
> +        foreach($fluxs as $flux) {
ici aussi vérifie les mises à jours de tes flux

2020-12-04 02:07 UTC, matthieuaudemard commented on Controller/FluxController.php
> +        if ($flux != null) {
tu peux utiliser la même proposition que je t'ai faite dans ton ArticleController et vérfier dans ton template si c'est null ou pas pour afficher un message approprié

2020-12-04 02:07 UTC, matthieuaudemard commented on Controller/FluxController.php
> +    public function allByFlux(int $id)
`allArticlesById(int $fluxId)` ?

2020-12-04 02:07 UTC, matthieuaudemard commented on Controller/FluxController.php
> +        $articles = $this->fluxManager->allByFlux($id);
si c'est bien allArticlesById(int $fluxId), dans ce cas là il le plus simple est d'utiliser directement ton ArticleManager et de créer ta méthode `allByFluxId(int $fluxId)`

2020-12-04 02:07 UTC, matthieuaudemard commented on config/config.sample..php
> +<?php
ton fichier s'appelle ` config/config.sample..php`, tu as mis 2 '.' après sample

2020-12-04 02:07 UTC, matthieuaudemard commented on manager/ArticleManager.php
> +        $stmt = $this->db->query('SELECT * FROM article');
penser qu'il pourrait être intéressant par la suite de pouvoir trier par critère (date, ordre alphabétique, catégorie) et par ordre croissant. tu peux mettre un todo  😉

2020-12-04 02:07 UTC, matthieuaudemard commented on manager/ArticleManager.php
> +    public function delete(int $id)
je suis pas sur que ça soit utilie comme je te l'ai dit de mettre un delete sur les article. enfin à voir, mais l'idée d'un flux c'est d'être averti de toutes les partutions. cependant c'est ton projet.

2020-12-04 02:07 UTC, matthieuaudemard commented on manager/ArticleManager.php
> +    public function update(Article $article): Article
est-ce pertinent de mettre à jour un article ? ton article il est créé à l'image de ton flux et n'est pas censé être modifié. le seul paramètre modifiable est celui qui permet de déterminé si l'utilisateur l'a lu ou non. on peut donc imaginer une méthode `setRead(int $articleId, bool $read)` qui permet en fonction de la valeur de `$read` (true/false) de le marqué comme lu ou non lu

2020-12-04 02:07 UTC, matthieuaudemard commented on manager/FluxManager.php
> +    public function one(int $id): ?Flux
quand tu veux afficher un flux, tu veux seulement afficher ses données (titre, adresse, image, ...) ou également les articles qu'il contient ? personnellement, en tant qu'utilisateur, je vois pas trop l'intérêt de voir seulement ses infos.

2020-12-04 02:07 UTC, matthieuaudemard commented on manager/FluxManager.php
> +        $stmt = $this->db->prepare('SELECT * FROM article WHERE rssId = :id');
le nom de cette méthode n'a pas de sens. tu es dans le manager de flux ... ça aurait un sens d'avoir un `ArticleManager::allByFluxId(int $id)`. je pense qu'en réalité le mieux c'est de récupérer tes articles quand tu veux récupérer ton flux. tu peux par exemple créer une méthode `FluxManager::one(int $id): Flux` qui ne renvoie que les données de ton flux (sans les articles) et une autre `FluxManager::oneWithArticles(int $id): Flux`  qui te renvoie le flux contenant également un tableau d'article.

ca implique de modifier ta classe Flux pour lui intégrer un tableau d'articles

2020-12-04 08:03 UTC, gillout commented on Controller/ArticleController.php
> +    private $db;
Comme je te l'ai dit hier, je l'ai enlevé de la classe mère car pas beaucoup de classes donc pas la peine pour l'instant de l'avoir dans la classe mère. Il est donc dans les 2 classes filles pour le moment.

2020-12-04 08:05 UTC, gillout commented on Controller/ArticleController.php
> +    public function __construct(PDO $db)
Je voulais pas recopier systématiquement cette classe afin de ne pas tout omper de Book. Je pourrais toujours le faire plus tard.

2020-12-04 08:11 UTC, gillout commented on Controller/ArticleController.php
> +            $article->setReleaseDate($article->getReleaseDate());
Je vais essayer de t'expliquer le pourquoi je fais ça, peut-être que tu auras une meilleure solution que celle-la.
L'affichage par défaut des informations d'es attributs ayant une date dans les vues est : Y-m-d H:i:s, hors je veux pouvoir formater la date à l'affichage comme ceci : d/m/Y H:i
Pour ce faire je dois faire repasser mes données dans le setter pour avoir le bon type, et ensuite je peux formater comme je veux.
Je te montrerai le problème plus clairement sur l'autre projet.

2020-12-04 08:12 UTC, gillout commented on Controller/ArticleController.php
> +            $article->setReleaseDate($article->getReleaseDate());
Même chose que ci-dessus.

2020-12-04 08:14 UTC, gillout commented on Controller/ArticleController.php
> +        } else {
Ok

2020-12-04 08:18 UTC, matthieuaudemard commented on Controller/ArticleController.php
> +            $article->setReleaseDate($article->getReleaseDate());
https://www.php.net/manual/fr/datetime.format.php -> ça peut peut-être t'aider pour le formatage des dates ?

2020-12-04 08:23 UTC, gillout commented on manager/ArticleManager.php
> +    public function delete(int $id)
Je me suis dit que cela servira plus tard, lors de la suppression complète d'un flux, soit appeler cette fonction dans un foreach pour supprimer un à un, soit la modifier un peu pour faire une suppression globale.
En fait, je pense que les fonctions insert, update, et delete sont des fonctions de bases à mettre systématiquement dans un manager au départ, enfin quand c'est pour un projet perso.

2020-12-04 08:24 UTC, gillout commented on manager/ArticleManager.php
> +    public function update(Article $article): Article
Il ne peut pas y avoir de mise à jour avec une modification de la date par exemple, si un article est enlevé ou ajouté au flux ?

2020-12-04 08:25 UTC, matthieuaudemard commented on manager/ArticleManager.php
> +    public function delete(int $id)
Pas faux. Après tu peux configurer la table Flux pour que la suppression d'un flux entraine la suppression de tous les articles (DELETE CASCADE)

2020-12-04 08:30 UTC, matthieuaudemard commented on manager/ArticleManager.php
> +    public function update(Article $article): Article
Effectivement j'y avais pas pensé, ça peut être une possibilité. A voir comment la mettre en pratique.

2020-12-04 08:39 UTC, gillout commented on manager/FluxManager.php
> +    public function one(int $id): ?Flux
C'est comme pour les fonctions insert, update, et delete, all et one sont des fonctions souvent utilisées donc une sorte de base, qui pourra être utilisée ou modifier plus tard, là aussi quand c'est pour un projet perso.

2020-12-04 08:51 UTC, gillout commented on manager/FluxManager.php
> +        $stmt = $this->db->prepare('SELECT * FROM article WHERE rssId = :id');
Oui, tu sais que les noms et moi, c'est pas ça. Au début je voulais ajouter ça commentaire de one() de flux : ", sans les articles", et l'autre : ", avec les articles".
Par contre, ce n'est pas encore clair pour moi de savoir où je dois mettre une fonction comme oneWithArticles, et pourquoi static plutôt que pas static.
Alors est-ce juste un simple choix sans conséquence : static dans une classe ou pas static dans l'autre classe ?

2020-12-04 08:55 UTC, gillout commented on .gitignore
> +/config/config.php
J'ai regardé mais il n'y a quasi rien sur la page et je ne vois pas quoi faire.

2020-12-04 09:04 UTC, matthieuaudemard commented on .gitignore
> +/config/config.php
Tu as un input, tu écris par exemple composer et ça va te générer un gitignore pour composer. Tu peux en mettre plusieurs par exemple : 'composer phpstorm windows' et ça va t'ajouter dans le gitignore tous les fichiers que génèrent qui sont générés par les 3 outils (ex: fichiers de conf windows, le répertoire vendor de composer, et le .idea de phpstorm qui n'apporte rien à ton projet et qui au contraire l'alourdissent). Par exemple que je fais du java, j'ai des fichiers compilé que je veux pas ajouter (*.class) parce que je veux juste envoyer le code de l'appli.

2020-12-04 11:51 UTC, gillout commented on .gitignore
> +/config/config.php
Je ne vois pas quoi ajouter de plus donc j'ai fait avec les 3.

2020-12-04 18:27 UTC, matthieuaudemard commented on Controller/ArticleController.php
> +            $article->setReleaseDate($article->getReleaseDate());
Tu pourrais créer un namespace `Adapter` dans lequel tu crées une classe `DateAdapter` qui va te permettre de gérer les transformations des dates. Tu peux rajouter une méthode `toString(DateTime $date): string` et éventuellement une autre `toDateTime(string $date): DateTime`

2020-12-05 20:19 UTC, matthieuaudemard commented on .gitignore
> +/config/config.php
Tu as bien ajouté les instructions à ton gitignore ce qui veut dire que git ne traquera plus les modifs des fichiers que tu as mentionné. Cependant ils sont tjs présents dans ton repo ([vendor](https://github.com/gillout/flux-rss/tree/flux-et-article/vendor), [.idea](https://github.com/gillout/flux-rss/tree/flux-et-article/.idea). Pour les enlever de git (et uniquement de git, ils resteront dans ton dossier) il faut taper la commande suivante : 
```bash
git rm -r vendor ./idea
```
- `rm` : pour supprimer
- `-r` : pour récursif parce qu'il s'agit de dossiers

2020-12-14 19:45 UTC, gillout commented on Controller/ArticleController.php
> +    public function __construct(PDO $db)
Ajoutée

2020-12-19 18:33 UTC, merged